resource_name: s3_sales
definition_type: source
definition_id: 69589781-7828-43c5-9f63-8925b1c1ccc2
definition_image: airbyte/source-s3
definition_version: 4.1.2
configuration:
  bucket: dagster-demo-001
  format:
    encoding: utf8
    filetype: csv
    delimiter: ','
    block_size: 10000
    quote_char: '"'
    double_quote: true
    infer_datatypes: true
    newlines_in_values: false
  schema: '{}'
  streams:
  - name: creditcard
    globs:
    - sales/creditcard.csv
    format:
      encoding: utf8
      filetype: csv
      delimiter: ','
      quote_char: '"'
      null_values: []
      true_values:
      - y
      - 'yes'
      - t
      - 'true'
      - 'on'
      - '1'
      double_quote: true
      false_values:
      - n
      - 'no'
      - f
      - 'false'
      - 'off'
      - '0'
      inference_type: None
      header_definition:
        header_definition_type: From CSV
      strings_can_be_null: true
      skip_rows_after_header: 0
      skip_rows_before_header: 0
    schemaless: false
    validation_policy: Emit Record
    days_to_sync_if_history_is_full: 3
  - name: customer
    globs:
    - sales/customer.csv
    format:
      encoding: utf8
      filetype: csv
      delimiter: ','
      quote_char: '"'
      null_values: []
      true_values:
      - y
      - 'yes'
      - t
      - 'true'
      - 'on'
      - '1'
      double_quote: true
      false_values:
      - n
      - 'no'
      - f
      - 'false'
      - 'off'
      - '0'
      inference_type: None
      header_definition:
        header_definition_type: From CSV
      strings_can_be_null: true
      skip_rows_after_header: 0
      skip_rows_before_header: 0
    schemaless: false
    validation_policy: Emit Record
    days_to_sync_if_history_is_full: 3
  - name: salesorderdetail
    globs:
    - sales/salesorderdetail.csv
    format:
      encoding: utf8
      filetype: csv
      delimiter: ','
      quote_char: '"'
      null_values: []
      true_values:
      - y
      - 'yes'
      - t
      - 'true'
      - 'on'
      - '1'
      double_quote: true
      false_values:
      - n
      - 'no'
      - f
      - 'false'
      - 'off'
      - '0'
      inference_type: None
      header_definition:
        header_definition_type: From CSV
      strings_can_be_null: true
      skip_rows_after_header: 0
      skip_rows_before_header: 0
    schemaless: false
    validation_policy: Emit Record
    days_to_sync_if_history_is_full: 3
  - name: salesorderheader
    globs:
    - sales/salesorderheader.csv
    format:
      encoding: utf8
      filetype: csv
      delimiter: ','
      quote_char: '"'
      null_values: []
      true_values:
      - y
      - 'yes'
      - t
      - 'true'
      - 'on'
      - '1'
      double_quote: true
      false_values:
      - n
      - 'no'
      - f
      - 'false'
      - 'off'
      - '0'
      inference_type: None
      header_definition:
        header_definition_type: From CSV
      strings_can_be_null: true
      skip_rows_after_header: 0
      skip_rows_before_header: 0
    schemaless: false
    validation_policy: Emit Record
    days_to_sync_if_history_is_full: 3
  - name: salesorderheadersalesreason
    globs:
    - sales/salesorderheadersalesreason.csv
    format:
      encoding: utf8
      filetype: csv
      delimiter: ','
      quote_char: '"'
      null_values: []
      true_values:
      - y
      - 'yes'
      - t
      - 'true'
      - 'on'
      - '1'
      double_quote: true
      false_values:
      - n
      - 'no'
      - f
      - 'false'
      - 'off'
      - '0'
      inference_type: None
      header_definition:
        header_definition_type: From CSV
      strings_can_be_null: true
      skip_rows_after_header: 0
      skip_rows_before_header: 0
    schemaless: false
    validation_policy: Emit Record
    days_to_sync_if_history_is_full: 3
  - name: salesreason
    globs:
    - sales/salesreason.csv
    format:
      encoding: utf8
      filetype: csv
      delimiter: ','
      quote_char: '"'
      null_values: []
      true_values:
      - y
      - 'yes'
      - t
      - 'true'
      - 'on'
      - '1'
      double_quote: true
      false_values:
      - n
      - 'no'
      - f
      - 'false'
      - 'off'
      - '0'
      inference_type: None
      header_definition:
        header_definition_type: From CSV
      strings_can_be_null: true
      skip_rows_after_header: 0
      skip_rows_before_header: 0
    schemaless: false
    validation_policy: Emit Record
    days_to_sync_if_history_is_full: 3
  - name: store
    globs:
    - sales/store.csv
    format:
      encoding: utf8
      filetype: csv
      delimiter: ','
      quote_char: '"'
      null_values: []
      true_values:
      - y
      - 'yes'
      - t
      - 'true'
      - 'on'
      - '1'
      double_quote: true
      false_values:
      - n
      - 'no'
      - f
      - 'false'
      - 'off'
      - '0'
      inference_type: None
      header_definition:
        header_definition_type: From CSV
      strings_can_be_null: true
      skip_rows_after_header: 0
      skip_rows_before_header: 0
    schemaless: false
    validation_policy: Emit Record
    days_to_sync_if_history_is_full: 3
  provider: {}
  aws_access_key_id: '**********'
  aws_secret_access_key: '**********'
