name: "analytics"
version: "1.0"

config-version: 2
require-dbt-version: [">=1.0.0"]

profile: "snowflake"

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seed"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
log-path: "logs"
clean-targets: ["target", "dbt_modules", "dbt_packages", "logs"]

quoting:
  database: false
  schema: false
  identifier: false

models:
  analytics:
    +materialized: table
    +transient: true 
    raw:
      +schema: raw
    serving:
      +schema: serving
